name: MinecraftItemInDB
version: '1.0-SNAPSHOT'
main: org.foodust.minecraftItemInDB.MinecraftItemInDB
api-version: '1.20'
authors: [ Foodust ]
libraries:
  - "org.postgresql:postgresql:42.7.3"
  - "org.springframework:spring-core:5.3.19"
  - "org.springframework.boot:spring-boot-starter-data-jpa:2.7.0"
  - "org.springframework:spring-orm:5.3.19"
  - "org.springframework:spring-context:5.3.19"
  - "org.springframework:spring-beans:5.3.19"
  - "org.springframework:spring-aop:5.3.19"
  - "org.springframework:spring-expression:5.3.19"
  - "org.reflections:reflections:0.10.2"
  - "org.hibernate:hibernate-core:5.6.9.Final"
description: Minecraft Item In DB
commands:
  아이템:
